---
title: "About"
---

------------------------------------------------------------------------

#### How I became an Ecologist

<p style="font-size: small">

<i> "Don't give it up! keep it up! Turn it upside down!" (Kara no Kokoro, Anly) </i>

</p>

I am Brazilian, a dedicated father and husband. Unlike many colleagues, I had never dreamed of being an ecologist or anything related. As a kid, I would go to forest fragments near home to catch fruits and see mushrooms. I would also snick around plants to see insects while helping my father with gardening. But it never came to my mind to actually work with it. I was not the kind of kid that would have a collection of insects or do experiments with frogs. I just enjoyed being connected to that nature.

I always wanted to be a Navy soldier. I never tried to be one, though. In my last high school year, I decided to be a Biologist. Not for doing research but to be a Biology Teacher. This idea came out after having Biology lectures that year. The new Biology Teacher would not use any supporting material in the classes, such as books or any other printed material, as every other teacher would. He simply would go to the board and write some topics. Then, he would discuss those topics with us. I got amazed by his didactics and wanted to be like him.

While doing my graduate studies in Biology, I could not do intern-ships to practice my lecturing skills because I had to work; otherwise, I would have to quit. I worked in a big bank for over six years while studying Biology. No time for teaching. I felt bad as if I were throwing away my years of dedication. So, after discussing this issue with my wife, I decided to quit my job at the bank and start a Master's degree in 2014. We had to change our lifestyle to be able to live with a Master's scholarship. We struggled, but we managed it.

While studying to obtain my Master's degree, I had the chance to teach in high school. I was doing well, but life had other paths to show me. After applying for a PhD through Twitter, I moved to Estonia in 2016. Who would have thought? I was about to start a PhD in Ecology and 11,000 km away from my hometown. Of course, this story has many ups and downs, many moments in which I doubted myself and others in which people questioned my capacity. But I am not only curious; I am also stubborn.

<br>

#### What I am doing now

Currently, I am the Principal Investigator of the project "Macroecology of rare species: global phylogenetic and functional patterns". When I was about to defend my PhD in 2021, I decided to apply for a Personal Research Grant offered annually by the [Estonian Research Council](https://etag.ee/en/). They have a category of grants dedicated to people who have obtained a PhD degree from Estonian universities to develop research projects at foreign R&D institutions. Like many PhD students, I was afraid of not getting any job and had only one chance to get this Estonian funding. So, while writing the thesis, I came up with an idea about investigating the contribution of rare species to ecological communities.

I got **curious** about rare species because I realised that my thesis discussed biodiversity patterns in ecological communities but focused on general patterns (without explicitly focusing on common or rare species). Common (and abundant) species are generally more studied than rare species. However, rare species are as important as common ones. And it was exciting to imagine their contribution to the assembly and functioning of ecological communities. So I sat down, wrote the project, and applied for the grant. In December 2021, I received an e-mail with the message **"...your application has been approved"**. I develop the project at the University of São Paulo, Brazil, in partnership with the University of Tartu, Estonia.

After many years of thinking about creating a website (*I think it has been over six years now*), I finally got it! I intend to make it a place where I share professional information and some not job-related creative things that sometimes happen to me. This website would not have been created if there were no excellent free material from which I learned or adapted some CSS and HTML pieces of code. A special thanks goes to [Sam Csik](https://github.com/samanthacsik/samanthacsik.github.io/tree/main) and [Marvin Schmitt](https://github.com/marvinschmitt), and of course, people involved in the construction of [Quarto](https://quarto.org/).
